### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by AlexanderDGeorge** [AlexanderDGeorge/Spotlofi#4]
[] user can login
[] user can sign up
[] user can logout
[] home page created with links to session controls

**Comment by SergeyGridin** [comment]
- [ ] Errors are not being rendered.
- [ ] No logout button
- [ ] Password is not being hidden. Use `type=password` for your inout field
- [ ] I am getting 500 error when trying to signup the user with following inputs: `{username: guest, email: 123, password: 123123}`
- [ ] remove your `console.log` from production.
- [ ] remove borders from buttons when the state is focused.
